server:
  port: 9007

spring:
  application:
    name: person-service
  threads:
    virtual:
      enabled: true
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${random.value}

  datasource:
    url: jdbc:postgresql://localhost:5432/person_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    root: INFO
    com.enterprise.person: DEBUG
    org.hibernate.SQL: DEBUG

# Person service config
person:
  code:
    prefix: "P"
    year-format: "yyyy"
